name = "luciddreamer-ai"
account_id = "049ff5e84ecf636b53b162cbb580aae6"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "PODCAST_KV"
id = "b9ac06cc53d248d0af745b9a7dddf91d"

[vars]
DEEPSEEK_API_KEY = ""

[[kv_namespaces]]
binding = "KG"
id = "b9ac06cc53d248d0af745b9a7dddf91d"
